#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER bot WITH PASSWORD '${DB_BOT_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO bot;
  GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO bot;
  GRANT SELECT ON ALL TABLES IN SCHEMA ${DB_SCHEMA} TO bot;
  ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA} GRANT SELECT ON TABLES TO bot;
EOSQL